[project]
name = "fastapi-with-openai-and-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "mcp>=1.13.1",
    "openai>=1.102.0",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
]
